ada:
  regressor__loss:
  - linear
  regressor__n_estimators:
  - 100
en:
  regressor__alpha:
  - 0.1
  regressor__l1_ratio:
  - 0.9
  regressor__max_iter:
  - 1000
plr:
  poli__degree:
  - 2
rfr:
  regressor__max_depth:
  - 20
  regressor__max_features:
  - 60
  regressor__min_samples_leaf:
  - 2
  regressor__n_estimators:
  - 150
svr:
  regressor__C:
  - 2
  regressor__epsilon:
  - 0.01
  regressor__kernel:
  - rbf
